### ISSUE TITLE
Ultimate AngularJS: Build a Real-World App from Scratch

### ISSUE THREAD

**Issue by icosta-cci** [costaivo/PlayGround-Angular#10]
https://www.udemy.com/ultimate-angularjs-course/

- [x] Course Overview

- [x] AngularJS Theory

- [x] Setting Up the Development Environment

- [x] Controllers, Scope, and Dependency Injection

- [x] Building the Structure of the Application

- [x] Introducing $http

- [x] CRUD and User Interface Refinement

- [x] Routing with UI Router

- [x] Setting Up a Backend with Firebase

- [x] Directives

**Comment by costaivo** [comment]
Completed on 4th Dec 2018
